name: auto-merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - reopened
      - unlocked

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Merge pull request
        uses: xtreamwayz/automerge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_STEP_DEBUG: true
